services:
  db:
    container_name: nsql-apache-db
    image: mongo:7.0.17
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: log_clustering
    volumes:
      - mongo_data:/data/db

  app:
    container_name: nsql-apache-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      MONGODB_URL: mongodb://db:27017
      DB_NAME: log_clustering
    ports:
      - "127.0.0.1:8000:8000"

  mongo-express:
    container_name: nsql-apache-mongo-express
    image: mongo-express:1.0.2
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://db:27017/log_clustering
    ports:
      - "127.0.0.1:8081:8081"

volumes:
  mongo_data:
